image: google/cloud-sdk:alpine

stages:
  - tests
  - deploy
  - clear

Testing:
  stage: tests
  only:
  - master
  script:
  - python3 -m unittest discover -v

Deploying:
  stage: deploy
  only:
  - master
  script:
  - echo $SERVICE_ACCOUNT > /tmp/$CI_PIPELINE_ID.json
  - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
  - gcloud config set project ba-serverless-testing
  - gcloud builds submit --tag gcr.io/ba-serverless-testing/ba-serverless-testing-image
  - gcloud run deploy ba-serverless-testing --image gcr.io/ba-serverless-testing/ba-serverless-testing-image --region europe-west1 --platform managed --allow-unauthenticated

Clearing:
  stage: clear
  script:
  - rm /tmp/$CI_PIPELINE_ID.json