image: google/cloud-sdk:alpine

stages:
  - test
  - deploy

testing:
  stage: test
  only:
  - master
  script:
  - which python3

deploying:
  stage: deploy
  only:
  - master
  script:
  - echo $SERVICE_ACCOUNT > /tmp/$CI_PIPELINE_ID.json
  - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
  - gcloud config set project ba-serverless-testing
  - gcloud builds submit --tag gcr.io/ba-serverless-testing/ba-serverless-testing-image
  - gcloud beta run deploy --image gcr.io/ba-serverless-testing/ba-serverless-testing-image --region europe-west1 --platform managed --allow-unauthenticated
