image: google/cloud-sdk:alpine

stages:
  - test
  - deploy

stage_test:
  stage: test
  only:
  - master
  script:
  - which python3

stage_deploy:
  stage: deploy
  only:
  - master
  script:
  - echo $SERVICE_ACCOUNT > /tmp/$CI_PIPELINE_ID.json
  - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
  - gcloud builds submit --tag gcr.io/ba-serverless-testing/ba-serverless-testing-image
  - gcloud beta run deploy --image gcr.io/ba-serverless-testing/ba-serverless-testing-image --region europe-west1 --platform managed --allow-unauthenticated
