# image: google/cloud-sdk:alpine

stages:
  - build
  - test
  - deploy

Build:
  stage: build
  image: docker:latest
  only:
  - master
  script:
  - docker build -t flask/serverless-testing .
  artifacts:
    paths:
      - /var/lib/docker

Test:
  stage: test
  image: docker:latest
  only:
  - master
  script:
  - docker run --name serverless-testing -p 8080:8080 flask/serverless-testing
  - docker exec serverless-testing python3 -m unittest discover -v

Deploy:
  stage: deploy
  image: google/cloud-sdk:alpine
  only:
  - master
  script:
  - echo $SERVICE_ACCOUNT > /tmp/$CI_PIPELINE_ID.json
  - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
  - gcloud config set project ba-serverless-testing
  - gcloud builds submit --tag eu.gcr.io/ba-serverless-testing/ba-serverless-testing-image
  - gcloud run deploy ba-serverless-testing --image eu.gcr.io/ba-serverless-testing/ba-serverless-testing-image --region europe-west1 --platform managed --allow-unauthenticated
  - rm /tmp/$CI_PIPELINE_ID.json